# Generated by Django 3.0.3 on 2020-06-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('State', models.CharField(choices=[('en', 'ENGLISH'), ('kn', 'KARNATAKA'), ('te', 'ANDRA_TELANGANA'), ('tn', 'TAMILNADU'), ('mr', 'MAHARASTRA'), ('gu', 'GUJARATH'), ('pa', 'PANJAB'), ('ml', 'KERALA'), ('ur', 'URDU'), ('bl', 'WESTBENGAL'), ('hi', 'HINDI')], default='ENGLISH', max_length=12)),
                ('Logo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('Language', models.CharField(choices=[('en', 'ENGLISH'), ('kn', 'KARNATAKA'), ('te', 'ANDRA_TELANGANA'), ('tn', 'TAMILNADU'), ('mr', 'MAHARASTRA'), ('gu', 'GUJARATH'), ('pa', 'PANJAB'), ('ml', 'KERALA'), ('ur', 'URDU'), ('bl', 'WESTBENGAL'), ('hi', 'HINDI')], default='ENGLISH', max_length=12)),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Notification_Date', models.CharField(max_length=100)),
                ('Number_Of_Posts', models.CharField(max_length=100)),
                ('LastDate', models.CharField(max_length=100)),
                ('Education', models.CharField(max_length=100)),
                ('Age_Limit', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Application_Fees', models.CharField(max_length=100)),
                ('Selection_Process', models.TextField()),
                ('How_To_Apply', models.TextField()),
                ('Pdf_link', models.CharField(max_length=100)),
                ('Official_Notification', models.CharField(max_length=100)),
                ('Selection_Process_KN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_TE', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_TA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_MR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_GU', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_PA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_ML', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_UR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_BN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Selection_Process_OR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_KN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_TE', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_TA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_MR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_GU', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_PA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_ML', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_UR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_BN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_OR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('How_To_Apply_HI', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_KN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_TE', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_TA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_MR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_GU', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_PA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_ML', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_UR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_BN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_OR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Name_HI', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_KN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_TE', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_TA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_MR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_GU', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_PA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_ML', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_UR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_BN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_OR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Department_HI', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_TE', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_TA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_MR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_GU', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_PA', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_ML', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_UR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_BN', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_OR', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_HI', models.TextField(blank=True, default='Dont Fill', null=True)),
                ('Location_KN', models.TextField(blank=True, default='Dont Fill', null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('MaterialId', models.AutoField(primary_key=True, serialize=False)),
                ('Language', models.CharField(choices=[('en', 'ENGLISH'), ('kn', 'KARNATAKA'), ('te', 'ANDRA_TELANGANA'), ('tn', 'TAMILNADU'), ('mr', 'MAHARASTRA'), ('gu', 'GUJARATH'), ('pa', 'PANJAB'), ('ml', 'KERALA'), ('ur', 'URDU'), ('bl', 'WESTBENGAL'), ('hi', 'HINDI')], default='ENGLISH', max_length=12)),
                ('JobName', models.CharField(max_length=500)),
                ('SubCategory', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('Books', models.CharField(choices=[('Question Papers', '1 Question Papers'), ('Syllabus', '2 Syllabus'), ('How to Prepare', '3 How to Prepare'), ('Books', '4 Books')], default='1 Question Papers', max_length=50)),
                ('Year', models.CharField(max_length=500)),
                ('Images', models.CharField(max_length=500)),
                ('Link', models.CharField(max_length=500)),
                ('Dept_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='English.Department')),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
